### ISSUE TITLE
Customise swipe actions

### ISSUE THREAD

**Issue by rbits0** [aeharding/wefwef#218] opened 2023-07-03 18:53 UTC
In Apollo you could customise the swipe actions, I had it set so right swipe was upvote and left swipe was downvote. In wefwef I have to swipe slow so I don't swipe too far, would be nice to be able to make both right swipe actions upvote.

**Comment by aeharding** [comment] 2023-07-03 20:12
Thanks, but dupe of #64

**Closed by aeharding** 2023-07-03 20:12 UTC
