### ISSUE TITLE
[feature]Block community 

### ISSUE THREAD

**Issue by DLRAM** [aeharding/wefwef#239] opened 2023-07-04 10:27 UTC
Able to block community just like in the other apps

**Comment by rsammelson** [comment] 2023-07-04 11:22
Duplicate of #40.

**Comment by aeharding** [comment] 2023-07-04 18:50
Thanks @rsammelson

**Comment by aeharding** [comment] 2023-07-04 18:51
FWIW, you can block in the lemmy UI for now.

**Closed by aeharding** 2023-07-04 18:50 UTC
Labels: enhancement, lemmy-parity
