### ISSUE TITLE
Pressing Back while viewing an image in the feed opens the community selection tab, thus losing feed progress 

### ISSUE THREAD

**Issue by GitBarns** [aeharding/wefwef#254] opened 2023-07-04 18:07 UTC
On Android, in compact mode in the main feed, click on an image, try to close it with the Back button, it closes the image but also opens the community tab which makes user lose their progress

Solution should be to simply close the image without opening the community tab

**Comment by GitBarns** [comment] 2023-07-04 18:10
Uploading Screen_Recording_20230704_110925_Chrome_1.mp4…

**Comment by GitBarns** [comment] 2023-07-04 18:11
Repro:

https://github.com/aeharding/wefwef/assets/136652942/4fe80ce0-4a5e-4be2-b053-202849c07851

**Comment by aeharding** [comment] 2023-07-04 18:56
Duplicate of #111

**Closed by aeharding** 2023-07-04 18:56 UTC
