### ISSUE TITLE
App locks up when going back from post and swiping to quickly

### ISSUE THREAD

**Issue by enghseb** [aeharding/wefwef#223] opened 2023-07-03 20:26 UTC
If you're viewing a post, swipe back to the feed and then start scrolling down to quickly, the app locks up for 1-3 seconds or so. Sometimes more.

**Comment by aeharding** [comment] 2023-07-03 21:10
I believe this is a dupe of #18

It's really, really annoying, but I thing it's a safari bug. It doesn't occur on Android from my experience.

If anyone is able to investigate further and/or find/submit an upstream bug in Safari, I would really, REALLY appreciate it 🙏

**Closed by aeharding** 2023-07-03 21:10 UTC
