### ISSUE TITLE
Please make the back button close the image not literally take you back. 

### ISSUE THREAD

**Issue by mbiggs-gresham** [aeharding/wefwef#178] opened 2023-07-02 18:24 UTC
Currently when you preview an image for a post, the (mobile/android) back button takes you to the page before. Please can this be changed so that the back button simply closes the image leaving you where you were before clicking preview. 

![image](https://github.com/aeharding/wefwef/assets/34435305/fc917e79-a830-4711-bb63-2f51a936aeb5)

**Comment by aeharding** [comment] 2023-07-02 19:05
Hi thanks. This is a dupe of #111

**Closed by aeharding** 2023-07-02 19:05 UTC
