### ISSUE TITLE
iOS Keyboard not opening on search 

### ISSUE THREAD

**Issue by deevejinga** [aeharding/wefwef#311] opened 2023-07-07 05:46 UTC
They keyboard gets stuck after a while and won’t open again if you try to use the search function. Only happens when you add the app to the Home Screen.

**Comment by sasuryynala** [comment] 2023-07-07 08:36
I've seen others reporting the same thing and I think the conclusion was that this is a iOS problem. Try restarting your device.

**Comment by deevejinga** [comment] 2023-07-07 08:50
That fixes it, but the problem return after a short while.

**Comment by sasuryynala** [comment] 2023-07-07 09:20
I did a bit of googling and apparently iOS doesn't like PWAs for some reason. Apple has "fixed" the problem multiple times but for some reason it keeps coming back.

**Comment by deevejinga** [comment] 2023-07-07 09:35
Cheers mate, I will use the website until there is a real app or another „fix“.

**Comment by deevejinga** [comment] 2023-07-07 09:50
Apparently this „fixes“ it: https://ferdychristant.com/keyboard-stuck-in-ios-add-to-homescreen-app-54aac3a37ff3

**Comment by aeharding** [comment] 2023-07-07 14:15
I use wefwef many times every day on my iPhone 13 mini, and I've never experienced this issue. I believe it is an iOS bug related to your setup; maybe an iOS app that's somehow breaking keyboard display due to an iOS bug.

If there's any pattern (for example, if you open a certain app then open wefwef and the keyboard is broken until restart), please open another bug here and I would be happy to forward this bug to Apple.

Until reproduction is available, I'm closing this issue.

**Closed by aeharding** 2023-07-07 14:15 UTC

**Comment by deevejinga** [comment] 2023-07-07 19:54
You are right, I fixed it by removing a spelling checker keyboard which I had installed, thanks for all the work!

**Comment by aeharding** [comment] 2023-07-08 02:07
@deevejinga What was the app? I will report this to Apple.

**Comment by deevejinga** [comment] 2023-07-08 08:25
LanguageTool it’s called.

**Comment by mdecourcy** [comment] 2023-07-08 18:04
I have LanguageTool installed on ff on android and also have this issue.
