### ISSUE TITLE
Bug: Error message covers navigation bar

### ISSUE THREAD

**Issue by SocietasEvanescentes** [aeharding/wefwef#252] opened 2023-07-04 17:12 UTC
It should be above the navigation bar, so it doesn't prevent someone from trying to fix the issue by retrying or going to a different tab. 

<img width="423" alt="Screenshot 2023-07-04 at 12 53 09 PM" src="https://github.com/aeharding/wefwef/assets/25782090/d6e1f947-3383-4eae-a41d-b8de45519ca8">

**Comment by rsammelson** [comment] 2023-07-04 17:58
Duplicate of #147.

**Closed** 2023-07-04 18:55 UTC
